redmine/config/routes.rb
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

Rails.application.routes.draw do
  root :to => 'welcome#index', :as => 'home'

  match 'login', :to => 'account#login', :as => 'signin', :via => [:get, :post]
  match 'logout', :to => 'account#logout', :as => 'signout', :via => [:get, :post]
  match 'account/twofa/confirm', :to => 'account#twofa_confirm', :via => :get
  match 'account/twofa/resend', :to => 'account#twofa_resend', :via => :post
  match 'account/twofa', :to => 'account#twofa', :via => [:get, :post]
  match 'account/register', :to => 'account#register', :via => [:get, :post], :as => 'register'
  match 'account/lost_password', :to => 'account#lost_password', :via => [:get, :post], :as => 'lost_password'
  match 'account/activate', :to => 'account#activate', :via => :get
  get 'account/activation_email', :to => 'account#activation_email', :as => 'activation_email'

  match '/news/preview', :controller => 'previews', :action => 'news', :as => 'preview_news', :via => [:get, :post, :put, :patch]
  match '/issues/preview', :to => 'previews#issue', :as => 'preview_issue', :via => [:get, :post, :put, :patch]
  match '/preview/text', :to => 'previews#text', :as => 'preview_text', :via => [:get, :post, :put, :patch]

  match 'projects/:id/wiki/destroy', :to => 'wikis#destroy', :via => [:get, :post]

  match 'boards/:board_id/topics/new', :to => 'messages#new', :via => [:get, :post], :as => 'new_board_message'
  get 'boards/:board_id/topics/:id', :to => 'messages#show', :as => 'board_message'
  match 'boards/:board_id/topics/quote/:id', :to => 'messages#quote', :via => [:get, :post]
  get 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'

  post 'boards/:board_id/topics/preview', :to => 'messages#preview', :as => 'preview_board_message'
  post 'boards/:board_id/topics/:id/replies', :to => 'messages#reply'
  post 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'
  post 'boards/:board_id/topics/:id/destroy', :to => 'messages#destroy'

  # Auto complete routes
  match '/issues/auto_complete', :to => 'auto_completes#issues', :via => :get, :as => 'auto_complete_issues'
  match '/wiki_pages/auto_complete', :to => 'auto_completes#wiki_pages', :via => :get, :as => 'auto_complete_wiki_pages'

  # Misc issue routes. TODO: move into resources
  match '/issues/context_menu', :to => 'context_menus#issues', :as => 'issues_context_menu', :via => [:get, :post]
  match '/issues/changes', :to => 'journals#index', :as => 'issue_changes', :via => :get
  match '/issues/:id/quoted', :to => 'journals#new', :id => /\d+/, :via => :post, :as => 'quoted_issue'

  resources :journals, :only => [:edit, :update] do
    member do
      get 'diff'
    end
  end

  get '/projects/:project_id/issues/gantt', :to => 'gantts#show', :as => 'project_gantt'
  get '/issues/gantt', :to => 'gantts#show'

  get '/projects/:project_id/issues/calendar', :to => 'calendars#show', :as => 'project_calendar'
  get '/issues/calendar', :to => 'calendars#show'

  get 'projects/:id/issues/report', :to => 'reports#issue_report', :as => 'project_issues_report'
  get 'projects/:id/issues/report/:detail', :to => 'reports#issue_report_details', :as => 'project_issues_report_details'

  get   '/issues/imports/new', :to => 'imports#new',
        :defaults => {:type => 'IssueImport'}, :as => 'new_issues_import'
  get   '/time_entries/imports/new', :to => 'imports#new',
        :defaults => {:type => 'TimeEntryImport'}, :as => 'new_time_entries_import'
  get   '/users/imports/new', :to => 'imports#new',
        :defaults => {:type => 'UserImport'}, :as => 'new_users_import'
  post  '/imports', :to => 'imports#create', :as => 'imports'
  get   '/imports/:id', :to => 'imports#show', :as => 'import'
  match '/imports/:id/settings', :to => 'imports#settings', :via => [:get, :post], :as => 'import_settings'
  match '/imports/:id/mapping', :to => 'imports#mapping', :via => [:get, :post], :as => 'import_mapping'
  match '/imports/:id/run', :to => 'imports#run', :via => [:get, :post], :as => 'import_run'

  match 'my/account', :controller => 'my', :action => 'account', :via => [:get, :put]
  match 'my/account/destroy', :controller => 'my', :action => 'destroy', :via => [:get, :post], :as => :delete_my_account
  match 'my/page', :controller => 'my', :action => 'page', :via => :get
  post 'my/page', :to => 'my#update_page'
  match 'my', :controller => 'my', :action => 'index', :via => :get # Redirects to my/page
  get 'my/api_key', :to => 'my#show_api_key', :as => 'my_api_key'
  post 'my/api_key', :to => 'my#reset_api_key'
  post 'my/atom_key', :to => 'my#reset_atom_key', :as => 'my_atom_key'
  match 'my/password', :controller => 'my', :action => 'password', :via => [:get, :post]
  match 'my/add_block', :controller => 'my', :action => 'add_block', :via => :post
  match 'my/remove_block', :controller => 'my', :action => 'remove_block', :via => :post
  match 'my/order_blocks', :controller => 'my', :action => 'order_blocks', :via => :post
  match 'my/twofa/activate/init', :controller => 'twofa', :action => 'activate_init', :via => :post
  match 'my/twofa/:scheme/activate/init', :controller => 'twofa', :action => 'activate_init', :via => :post
  match 'my/twofa/:scheme/activate/confirm', :controller => 'twofa', :action => 'activate_confirm', :via => :get
  match 'my/twofa/:scheme/activate', :controller => 'twofa', :action => 'activate', :via => [:get, :post]
  match 'my/twofa/:scheme/deactivate/init', :controller => 'twofa', :action => 'deactivate_init', :via => :post
  match 'my/twofa/:scheme/deactivate/confirm', :controller => 'twofa', :action => 'deactivate_confirm', :via => :get
  match 'my/twofa/:scheme/deactivate', :controller => 'twofa', :action => 'deactivate', :via => [:get, :post]
  match 'my/twofa/select_scheme', :controller => 'twofa', :action => 'select_scheme', :via => :get
  match 'my/twofa/backup_codes/init', :controller => 'twofa_backup_codes', :action => 'init', :via => :post
  match 'my/twofa/backup_codes/confirm', :controller => 'twofa_backup_codes', :action => 'confirm', :via => :get
  match 'my/twofa/backup_codes/create', :controller => 'twofa_backup_codes', :action => 'create', :via => [:get, :post]
  match 'my/twofa/backup_codes', :controller => 'twofa_backup_codes', :action => 'show', :via => [:get]
  match 'users/:user_id/twofa/deactivate', :controller => 'twofa', :action => 'admin_deactivate', :via => :post

  match '/users/context_menu', to: 'context_menus#users', as: :users_context_menu, via: [:get, :post]
  resources :users do
    collection do
      delete 'bulk_destroy'
    end
    resources :memberships, :controller => 'principal_memberships'
    resources :email_addresses, :only => [:index, :create, :update, :destroy]
  end

  post 'watchers/watch', :to => 'watchers#watch', :as => 'watch'
  delete 'watchers/watch', :to => 'watchers#unwatch'
  get 'watchers/new', :to => 'watchers#new', :as => 'new_watchers'
  post 'watchers', :to => 'watchers#create'
  post 'watchers/append', :to => 'watchers#append'
  delete 'watchers', :to => 'watchers#destroy'
  get 'watchers/autocomplete_for_mention', to: 'watchers#autocomplete_for_mention', via: [:get]
  get 'watchers/autocomplete_for_user', :to => 'watchers#autocomplete_for_user'
  # Specific routes for issue watchers API
  post 'issues/:object_id/watchers', :to => 'watchers#create', :object_type => 'issue'
  delete 'issues/:object_id/watchers/:user_id' => 'watchers#destroy', :object_type => 'issue'

  resources :projects do
    collection do
      get 'autocomplete'
      delete 'bulk_destroy'
    end

    member do
      get 'settings(/:tab)', :action => 'settings', :as => 'settings'
      match 'archive', :via => [:post, :put]
      match 'unarchive', :via => [:post, :put]
      match 'close', :via => [:post, :put]
      match 'reopen', :via => [:post, :put]
      match 'copy', :via => [:get, :post]
      match 'bookmark', :via => [:delete, :post]
    end

    shallow do
      resources :memberships, :controller => 'members' do
        collection do
          get 'autocomplete'
        end
      end
    end

    resource :enumerations, :controller => 'project_enumerations', :only => [:update, :destroy]

    get 'issues/:copy_from/copy', :to => 'issues#new', :as => 'copy_issue'
    resources :issues, :only => [:index, :new, :create]
    # Used when updating the form of a new issue
    post 'issues/new', :to => 'issues#new'

    resources :files, :only => [:index, :new, :create]

    resources :versions, :except => [:index, :show, :edit, :update, :destroy] do
      collection do
        put 'close_completed'
      end
    end
    get 'versions.:format', :to => 'versions#index'
    get 'roadmap', :to => 'versions#index', :format => false
    get 'versions', :to => 'versions#index'

    resources :news, :except => [:show, :edit, :update, :destroy]
    resources :time_entries, :controller => 'timelog', :except => [:show, :edit, :update, :destroy] do
      get 'report', :on => :collection
    end
    resources :queries, :only => [:new, :create]
    shallow do
      resources :issue_categories
    end
    resources :documents, :except => [:show, :edit, :update, :destroy]
    resources :boards
    shallow do
      resources :repositories, :except => [:index, :show] do
        member do
          match 'committers', :via => [:get, :post]
        end
      end
    end

    match 'wiki/index', :controller => 'wiki', :action => 'index', :via => :get
    resources :wiki, :except => [:index, :create], :as => 'wiki_page' do
      member do
        get 'rename'
        post 'rename'
        get 'history'
        get 'diff'
        match 'preview', :via => [:post, :put, :patch]
        post 'protect'
        post 'add_attachment'
      end
      collection do
        get 'export'
        get 'date_index'
        post 'new'
      end
    end

redmine/app/controllers/imports_controller.rb
# frozen_string_literal: true

# Redmine - project management software
# Copyright (C) 2006-  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

require 'csv'

class ImportsController < ApplicationController
  before_action :find_import, :only => [:show, :settings, :mapping, :run]
  before_action :authorize_import

  layout :import_layout

  helper :issues
  helper :queries

  def new
    @import = import_type.new
  end

  def create
    @import = import_type.new
    @import.user = User.current
    @import.file = params[:file]
    @import.set_default_settings(:project_id => params[:project_id])

    if @import.save
      redirect_to import_settings_path(@import)
    else
      render :action => 'new'
    end
  end

  def show
  end

  def settings
    if request.post? && @import.parse_file
      if @import.total_items == 0
        flash.now[:error] = l(:error_no_data_in_file)
      else
        redirect_to import_mapping_path(@import)
      end
    end

  rescue CSV::MalformedCSVError, EncodingError => e
    if e.is_a?(CSV::MalformedCSVError) && !e.message.include?('Invalid byte sequence')
      flash.now[:error] = l(:error_invalid_csv_file_or_settings, e.message)
    else
      flash.now[:error] = l(:error_invalid_file_encoding, :encoding => ERB::Util.h(@import.settings['encoding']))
    end
  rescue SystemCallError => e
    flash.now[:error] = l(:error_can_not_read_import_file)
  end

  def mapping
    @custom_fields = @import.mappable_custom_fields

    if request.get?
      auto_map_fields
    elsif request.post?
      respond_to do |format|
        format.html do
          if params[:previous]
            redirect_to import_settings_path(@import)
          else
            redirect_to import_run_path(@import)
          end
        end
        format.js # updates mapping form on project or tracker change
      end
    end
  end

  def run
    if request.post?
      @current = @import.run(
        :max_items => max_items_per_request,
        :max_time => 10.seconds
      )
      respond_to do |format|
        format.html do
          if @import.finished?
            redirect_to import_path(@import)
          else
            redirect_to import_run_path(@import)
          end
        end
        format.js
      end
    end
  end

  def current_menu(project)
    if import_layout == 'admin'
      nil
    else
      :application_menu
    end
  end

  private

  def find_import
    @import = Import.where(:user_id => User.current.id, :filename => params[:id]).first
    if @import.nil?
      render_404
      return
    elsif @import.finished? && action_name != 'show'
      redirect_to import_path(@import)
      return
    end
    update_from_params if request.post?
  end

  def update_from_params
    if params[:import_settings].present?
      @import.settings ||= {}
      @import.settings.merge!(params[:import_settings].to_unsafe_hash)
      @import.save!
    end
  end

  def max_items_per_request
    5
  end

  def import_layout
    import_type && import_type.layout || 'base'
  end

  def menu_items
    menu_item = import_type ? import_type.menu_item : nil
    {self.controller_name.to_sym => {:actions => {}, :default => menu_item}}
  end

  def authorize_import
    return render_404 unless import_type
    return render_403 unless import_type.authorized?(User.current)
  end

  def import_type
    return @import_type if defined? @import_type

    @import_type =
      if @import
        @import.class
      else
        type =
          begin
            Object.const_get(params[:type])
          rescue
            nil
          end
        type && type < Import ? type : nil
      end
  end

  def auto_map_fields
    # Try to auto map fields only when settings['enconding'] is present
    # otherwhise, the import fails for non UTF-8 files because the headers
    # cannot be retrieved (Invalid byte sequence in UTF-8)
    return if @import.settings['encoding'].blank?

    mappings = @import.settings['mapping'] ||= {}
    headers = @import.headers.map{|header| header&.downcase}

    # Core fields
    import_type::AUTO_MAPPABLE_FIELDS.each do |field_nm, label_nm|
      next if mappings.include?(field_nm)

      index = headers.index(field_nm) || headers.index(l(label_nm).downcase)
      if index
        mappings[field_nm] = index
      end
    end

    # Custom fields
    @custom_fields.each do |field|
      field_nm = "cf_#{field.id}"
      next if mappings.include?(field_nm)

      index = headers.index(field_nm) || headers.index(field.name.downcase)
      if index
        mappings[field_nm] = index
      end
    end
    mappings
  end
end

redmine/app/helpers/imports_helper.rb
# frozen_string_literal: true

# Redmine - project management software
# Copyright (C) 2006-  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module ImportsHelper
  def import_title
    l(:"label_import_#{import_partial_prefix}")
  end

  def import_partial_prefix
    @import.class.name.sub('Import', '').underscore.pluralize
  end

  def options_for_mapping_select(import, field, options={})
    tags = "".html_safe
    blank_text = options[:required] ? "-- #{l(:actionview_instancetag_blank_option)} --" : "&nbsp;".html_safe
    tags << content_tag('option', blank_text, :value => '')
    tags << options_for_select(import.columns_options, import.mapping[field])
    if values = options[:values]
      tags << content_tag('option', '--', :disabled => true)
      tags << options_for_select(values.map {|text, value| [text, "value:#{value}"]}, import.mapping[field] || options[:default_value])
    end
    tags
  end

  def mapping_select_tag(import, field, options={})
    name = "import_settings[mapping][#{field}]"
    select_tag name, options_for_mapping_select(import, field, options), :id => "import_mapping_#{field}"
  end

  # Returns the options for the date_format setting
  def date_format_options
    Import::DATE_FORMATS.map do |f|
      format = f.delete('%').gsub(/[dmY]/) do
        {'d' => 'DD', 'm' => 'MM', 'Y' => 'YYYY'}[$&]
      end
      [format, f]
    end
  end
end

redmine/app/views/imports/_issues_mapping.js.erb
$('#fields-mapping').html('<%= escape_javascript(render :partial => 'issues_fields_mapping') %>');

redmine/app/views/imports/_issues_relations_mapping.html.erb
<div class="splitcontent">
  <div class="splitcontentleft">
    <p>
      <label for="import_mapping_unique_id"><%= l(:field_unique_id) %></label>
      <%= mapping_select_tag @import, 'unique_id' %>
    </p>
    <p>
      <label for="import_settings_mapping_parent_issue_id"><%= l(:field_parent_issue) %></label>
      <%= mapping_select_tag @import, 'parent_issue_id' %>
    </p>

    <p>
      <label for="import_settings_mapping_relation_duplicates"><%= l(:label_duplicates) %></label>
      <%= mapping_select_tag @import, 'relation_duplicates' %>
    </p>

    <p>
      <label for="import_settings_mapping_relation_duplicated"><%= l(:label_duplicated_by) %></label>
      <%= mapping_select_tag @import, 'relation_duplicated' %>
    </p>

    <p>
      <label for="import_settings_mapping_relation_blocks"><%= l(:label_blocks) %></label>
      <%= mapping_select_tag @import, 'relation_blocks' %>
    </p>

    <p>
      <label for="import_settings_mapping_relation_blocked"><%= l(:label_blocked_by) %></label>
      <%= mapping_select_tag @import, 'relation_blocked' %>
    </p>
  </div>

  <div class="splitcontentright">
    <p></p>
    <p>
      <label for="import_settings_mapping_relation_relates"><%= l(:label_relates_to) %></label>
      <%= mapping_select_tag @import, 'relation_relates' %>
    </p>

    <p>
      <label for="import_settings_mapping_relation_precedes"><%= l(:label_precedes) %></label>
      <%= mapping_select_tag @import, 'relation_precedes' %>
    </p>

    <p>
      <label for="import_settings_mapping_relation_follows"><%= l(:label_follows) %></label>
      <%= mapping_select_tag @import, 'relation_follows' %>
    </p>

    <p>
      <label for="import_settings_mapping_relation_copied_to"><%= l(:label_copied_to) %></label>
      <%= mapping_select_tag @import, 'relation_copied_to' %>
    </p>

    <p>
      <label for="import_settings_mapping_relation_copied_from"><%= l(:label_copied_from) %></label>
      <%= mapping_select_tag @import, 'relation_copied_from' %>
    </p>
  </div>
</div>

redmine/app/views/imports/_issues_saved_objects.html.erb
<ul id="saved-items">
  <% saved_objects.each do |issue| %>
    <li><%= link_to_issue issue %></li>
  <% end %>
</ul>

<p><%= link_to l(:label_issue_view_all), issues_path(:set_filter => 1, :status_id => '*', :issue_id => saved_objects.map(&:id).join(',')) %></p>

redmine/app/views/imports/_time_entries_fields_mapping.html.erb
<p>
  <label for="import_mapping_project_id"><%= l(:label_project) %></label>
  <%= select_tag 'import_settings[mapping][project_id]',
        options_for_select(project_tree_options_for_select(@import.allowed_target_projects, :selected => @import.project)),
        :id => 'import_mapping_project_id' %>
</p>
<p>
  <label for="import_mapping_activity"><%= l(:field_activity) %></label>
  <%= mapping_select_tag @import, 'activity', :required => true,
        :values => @import.allowed_target_activities.sorted.map {|t| [t.name, t.id]} %>
</p>

<div class="splitcontent">
  <div class="splitcontentleft">
  <% if User.current.allowed_to?(:log_time_for_other_users, @import.project) %>
    <p>
      <label for="import_mapping_user"><%= l(:field_user) %></label>
      <%= mapping_select_tag @import, 'user', :required => true,
            :values => @import.allowed_target_users.map {|u| [u.name, u.id]}, :default_value => "value:#{User.current.id}" %>
    </p>
  <% end %>
  <p>
    <label for="import_mapping_issue_id"><%= l(:field_issue) %></label>
    <%= mapping_select_tag @import, 'issue_id' %>
  </p>
  <p>
    <label for="import_mapping_spent_on"><%= l(:field_spent_on) %></label>
    <%= mapping_select_tag @import, 'spent_on', :required => true %>
  </p>
  <p>
    <label for="import_mapping_hours"><%= l(:field_hours) %></label>
    <%= mapping_select_tag @import, 'hours', :required => true %>
  </p>
  <p>
    <label for="import_mapping_comments"><%= l(:field_comments) %></label>
    <%= mapping_select_tag @import, 'comments' %>
  </p>
  </div>

  <div class="splitcontentright">
  <% @custom_fields.each do |field| %>
    <p>
      <label for="import_mapping_cf_<%= field.id %>"><%= field.name %></label>
      <%= mapping_select_tag @import, "cf_#{field.id}", :required => field.is_required? %>
    </p>
  <% end %>
  </div>
</div>

redmine/app/views/imports/_time_entries_mapping.html.erb
<fieldset class="box tabular">
  <legend><%= l(:label_fields_mapping) %></legend>
  <div id="fields-mapping">
    <%= render :partial => 'time_entries_fields_mapping' %>
  </div>
</fieldset>

<%= javascript_tag do %>
$(document).ready(function() {
  $('#fields-mapping').on('change', '#import_mapping_project_id', function(){
    $.ajax({
      url: '<%= import_mapping_path(@import, :format => 'js') %>',
      type: 'post',
      data: $('#import-form').serialize()
    });
  });
});
<% end %>

redmine/app/views/imports/_users_fields_mapping.html.erb
<div class="splitcontent">
  <div class="splitcontentleft">
  <p>
    <label for="import_mapping_login"><%= l(:field_login) %></label>
    <%= mapping_select_tag @import, 'login', :required => true %>
  </p>
  <p>
    <label for="import_mapping_firstname"><%= l(:field_firstname) %></label>
    <%= mapping_select_tag @import, 'firstname', :required => true %>
  </p>
  <p>
    <label for="import_mapping_lastname"><%= l(:field_lastname) %></label>
    <%= mapping_select_tag @import, 'lastname', :required => true %>
  </p>
  <p>
    <label for="import_mapping_mail"><%= l(:field_mail) %></label>
    <%= mapping_select_tag @import, 'mail' %>
  </p>
  <p>
    <label for="import_mapping_language"><%= l(:field_language) %></label>
    <%= mapping_select_tag @import, 'language' %>
  </p>
  <p>
    <label for="import_mapping_admin"><%= l(:field_admin) %></label>
    <%= mapping_select_tag @import, 'admin' %>
  </p>
  <p>
    <label for="import_mapping_auth_source_id"><%= l(:field_auth_source) %></label>
    <%= mapping_select_tag @import, 'auth_source' %>
  </p>
  <p>
    <label for="import_mapping_password"><%= l(:field_password) %></label>
    <%= mapping_select_tag @import, 'password' %>
  </p>
  <p>
    <label for="import_mapping_must_change_passwd"><%= l(:field_must_change_passwd) %></label>
    <%= mapping_select_tag @import, 'must_change_passwd' %>
  </p>
  <p>
    <label for="import_mapping_status"><%= l(:field_status) %></label>
    <%= mapping_select_tag @import, 'status' %>
  </p>
  </div>

  <div class="splitcontentright">
  <% @custom_fields.each do |field| %>
    <p>
      <label for="import_mapping_cf_<%= field.id %>"><%= field.name %></label>
      <%= mapping_select_tag @import, "cf_#{field.id}", :required => field.is_required? %>
    </p>
  <% end %>
  </div>
</div>

redmine/app/views/imports/_users_mapping.js.erb
$('#fields-mapping').html('<%= escape_javascript(render :partial => 'users_fields_mapping') %>');

redmine/app/views/imports/_users_saved_objects.html.erb
<table id="saved-items" class="list">
  <thead>
  <tr>
    <th><%= t(:field_login) %></th>
    <th><%= t(:field_firstname) %></th>
    <th><%= t(:field_lastname) %></th>
    <th><%= t(:field_mail) %></th>
    <th><%= t(:field_admin) %></th>
    <th><%= t(:field_status) %></th>
  </tr>
  </thead>
  <tbody>
  <% saved_objects.each do |user| %>
  <tr>
    <td><%= avatar(user, :size => "14") %><%= link_to user.login, edit_user_path(user) %></td>
    <td><%= user.firstname %></td>
    <td><%= user.lastname %></td>
    <td><%= mail_to(user.mail) %></td>
    <td><%= checked_image user.admin? %></td>
    <td><%= l(("status_#{User::LABEL_BY_STATUS[user.status]}")) %>
  </tr>
  <% end %>
  </tbody>
</table>

redmine/app/views/imports/mapping.html.erb
<h2><%= import_title %></h2>

<%= form_tag(import_mapping_path(@import), :id => "import-form") do %>
  <%= render :partial => "#{import_partial_prefix}_mapping" %>

  <fieldset class="box">
    <legend><%= l(:label_file_content_preview) %></legend>

    <div class="autoscroll">
      <table class="sample-data">
      <% @import.first_rows.each do |row| %>
        <tr>
          <%= row.map {|c| content_tag 'td', truncate(c.to_s, :length => 50) }.join("").html_safe %>
        </tr>
      <% end %>
      </table>
    </div>
  </fieldset>

  <p>
    <%= button_tag("\xc2\xab " + l(:label_previous), :name => 'previous') %>
    <%= submit_tag l(:button_import) %>
  </p>
<% end %>

<%= javascript_tag do %>
$(document).ready(function() {
  $('#import-form').submit(function(){
    $('#import-details').show().addClass('ajax-loading');
    $('#import-progress').progressbar({value: 0, max: <%= @import.total_items || 0 %>});
  });
});
<% end %>

redmine/app/views/imports/mapping.js.erb
<%= render :partial => "#{import_partial_prefix}_mapping" %>

redmine/app/views/imports/new.html.erb
<h2><%= import_title %></h2>

<%= form_tag(imports_path, :multipart => true) do %>
  <%= hidden_field_tag 'type', @import.type %>
  <%= hidden_field_tag 'project_id', params[:project_id] %>
  <fieldset class="box">
    <legend><%= l(:label_select_file_to_import) %> (CSV)</legend>
    <p>
      <%= file_field_tag 'file' %>
    </p>
  </fieldset>
  <p><%= submit_tag l(:label_next).html_safe + " &#187;".html_safe, :name => nil %></p>
<% end %>

redmine/app/views/imports/run.js.erb
$('#import-progress').progressbar({value: <%= @current.to_i %>});
$('#progress-label').text("<%= @current.to_i %> / <%= @import.total_items.to_i %>");

<% if @import.finished? %>
window.location.href='<%= import_path(@import) %>';
<% else %>
$.ajax({
  url: '<%= import_run_path(@import, :format => 'js') %>',
  type: 'post'
});
<% end %>